### ISSUE TITLE
Create a basic builder

### ISSUE THREAD

**Issue by reitmas32** [reitmas32/Next#16]
### Example of config.yaml

```yaml
basic_release:
    base: basic
    c_compiler: gcc
    cxx_compiler: g++
    linker: ld
    files_cxx:
      - main.cpp
      - src/func/suma.cpp
      - src/structs/*.cc

    files_c:
      - main_of_c.c
      - src/func/suma.c
      - src/structs/*.c

    c_compiler_regex:
      $C $FILE -o #FILE.o
    cxx_compiler_regex:
      $CXX $FILE -o #FILE.o

    ld_regex:
      $LD $FILES -lgl -pthread
```

**Comment by reitmas32** [comment]
Finish working in [https://github.com/reitmas32/Next/commit/37bfbe1a0c5f707f5f7e186b6db6693ff7b3d23d](url) 
Create basic builder examples use is:
``` yaml
  basic_minim:
    base: basic
    source_cxx:
      - src/*.cpp
    source_c:
      - src/*.c

  basic_release:
    base: basic
    c_compiler: gcc
    cxx_compiler: clang++
    linker: ld
    source_x: [main.cpp, main.hcp]
    source_cxx:
      - src/main.cpp
      - src/func/suma.cpp
      - src/suma.cpp
      - src/structs/*.cpp
    # extension_files:
    #   - .cpp
    #   - .c
    #   - .cc
    c_compiler_regex:
      $C $FILE -o $FILE.o -c
    cxx_compiler_regex:
      $CXX -c $FILE -o $FILE_OUT -lGL -ptheard
    ld_regex:
      $LD $FILES $FILE_OUT -std=c++20

  basic_debug:
    base: basic
    name_out: my_app
    source_cxx:
      - src/*.cpp

    source_c:
      - src/*.c
    c_compiler_regex:
      $C -c $FILE -o $FILE_OUT
    cxx_compiler_regex:
      $CXX -c $FILE -o $FILE_OUT

    linker_regex:
      $LD $FILES -lstdc++ -o $FILE_OUT
```
